language: android
jdk: oraclejdk7
sudo: false

notifications:
  # Slack notification on failure (secured token).
  slack:
    rooms:
      secure: sOTcwi1DT0lJykB/smJQwJ5lQblg9jc5PtLsTu4euI/P4nCv1CPu5DVZ1aDwXL6TPDUO5uEwbzbjVFZzrl2nFdAV9XvGT3wL3Zrm2Y5HBtwi8JWdbc4dYR/xobJlIg7HRczXwoFt6yls4BUayNJJbZFV9q0ftmUSe77Pag/ZWQw=
    on_failure: always
    on_success: change

android:
  components:
    - extra-android-m2repository
    - extra-android-support
    - build-tools-23.0.1
    - android-23

env:
  global:
    - GRADLE_OPTS="-XX:MaxPermSize=4g -Xmx4g"
    - ANDROID_SDKS=android-14
    - ANDROID_TARGET=android-14
    # Username
    - secure: "YChsdOlmprsul75Wp96y63eUp0ZFafM9f1Syi1S6d1AewfIvaJmWw+cq26vQPE8868KJfhLvSH2eQJ67/jR4agUs9Z4vWlD4zYV+PSA0l3dXh2LIkBaJ28ACdpvFmZzh/gZpcNLEyBu160K9afKx9TSc40eiQgHAYjTvqbnq7H4="
    # Password
    - secure: "JootE3YTPaKW6tbDBH0XdpjUUQxfSHQO5Ji3a1zfYRto4fttaNW8m3I7UJBQa62lWD+TorvsgFX6d2YrBIe6RS07Hn5kN/iblC7Eh7wXpvj8K24dZKboSeTXxkjOmbqpk9eQiQd32uUeXqCPzrZYpTYzBCbEjROGs+7OT0fN1QQ="
    # Test Object API Key
    - secure: "nrEW1yrh5lL1U+NXPO4WTl5zXTTefS+C27ueF++uMLgl83ICtW35NClNqprWJuEa8aJzdZWE7Vi1jXyvLuzopqvOhItEH+8k3LIN7EM/R212gbKLzUditl1vT47D4qQk4mEElCo3ju8Lp7QGdn1rQV2wDtDYVcqVpqtWM+FzzT4="
    - "TESTOBJECT=1"
#    - "SAUCE=1"

install:
  # Setup gradle.properties
  - cp WordPress/gradle.properties-example WordPress/gradle.properties

addons:
  sauce_connect:
    username: "srstancil"
    access_key:
      secure: "YFkTrLnL2yOUbhJK4a08AK9gLAk7WPCvu78MvnVv0W7XajLq+7/bdlQtME0MXz5OuvRFalF0Kv2sxZjLGmUi/EJ/zkVlECCWt9kBL4vxMjI7f4J/TiP9Q+QCuupfr1pFUXT6npcflR8LOPMxAzkdPbtZeC9/3qAu/VyrUPTkQfs="

before_script:
  - npm install

script:
  # Temporarily removing to speed up first hack at testing - ./gradlew -PdisablePreDex build
  - npm test
